#!/usr/bin/env python3
"""Turn a supplier's price list (CSV) into site/onorder.js.

These are ON-ORDER items — things the counter doesn't stock, but can source for a
customer from a named supplier (one-word name, e.g. "Rohit"). They ride in the same
catalogue as in-stock products (same category, filters and search), flagged so the UI
can mark them clearly and price them from the dealer cost.

Pricing mirrors the in-stock rule: the supplier's dealer cost (NLC) is treated as the
GST-inclusive cost, written as `costIncl`, and the web app (site/app.js) applies the
same margin + rounding to produce the selling price. The list price (MRP) is carried
alongside for the staff-only tap-to-reveal detail.

Input CSV columns (header row required):
    series,capacity_ton,star,model,mrp,nlc

Usage:
    python tools/generate_supplier.py tools/rohit_daikin_june2026.csv \
        --supplier Rohit --brand Daikin --valid "June 2026"

Stdlib only — no third-party dependencies.
"""
import argparse
import csv
import json
import os
import sys

# Long price-list series names -> short label used as a filter chip / tag.
SERIES_LABELS = {
    "highest efficiency": "Highest Efficiency",
    "waizu": "Waizu",
    "wifi": "Wifi",
    "premium": "Premium",
    "standard": "Standard",
    "standard non inverter": "Standard",
    "hot & cold": "Hot & Cold",
    "hot and cold": "Hot & Cold",
}


def series_label(raw):
    return SERIES_LABELS.get(raw.strip().lower(), raw.strip())


def compressor_of(raw_series):
    return "Fixed Speed" if "non inverter" in raw_series.strip().lower() else "Inverter"


def ton_label(v):
    return f"{float(v):g} Ton"


def main():
    ap = argparse.ArgumentParser(description="Generate site/onorder.js from a supplier price list CSV.")
    ap.add_argument("csv", help="Path to the supplier price-list CSV")
    ap.add_argument("--supplier", required=True, help="One-word supplier name (e.g. Rohit)")
    ap.add_argument("--brand", required=True, help="Brand the list covers (e.g. Daikin)")
    ap.add_argument("--valid", required=True, help="Price-list validity label (e.g. \"June 2026\")")
    ap.add_argument("--category", default="Air Conditioner", help="Catalogue category (default: Air Conditioner)")
    ap.add_argument("--gst", type=int, default=18, help="GST rate, whole percent (default: 18)")
    ap.add_argument("--out", default=None, help="Output path (default: <repo>/site/onorder.js)")
    args = ap.parse_args()

    out = args.out or os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "site", "onorder.js"
    )

    items = []
    with open(args.csv, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            if not row.get("model"):
                continue
            raw_series = row["series"]
            ton = row["capacity_ton"].strip()
            star = row["star"].strip()
            model = row["model"].strip().upper()
            mrp = int(round(float(row["mrp"])))
            nlc = int(round(float(row["nlc"])))
            label = series_label(raw_series)
            name = f"{args.brand.upper()} {label.upper()} {float(ton):g}TON {star}* {model}"
            items.append({
                "name": name,
                "category": args.category,
                "attributes": {
                    "Brand": args.brand,
                    "Type": "Split",
                    "Capacity": ton_label(ton),
                    "Star Rating": f"{star} Star",
                    "Compressor": compressor_of(raw_series),
                    "Series": label,
                },
                "stock": 0,
                "onOrder": True,
                "supplier": args.supplier,
                "priceList": args.valid,
                "gst": args.gst,
                "costIncl": nlc,   # dealer cost drives the selling price (see app.js)
                "mrp": mrp,        # list price, shown in staff-only detail
            })

    if not items:
        sys.exit(f"No rows read from {args.csv}")

    header = (
        "// Auto-generated by tools/generate_supplier.py — do not edit by hand.\n"
        f"// On-order items from supplier \"{args.supplier}\" · {args.brand} price list · {args.valid}.\n"
        "// costIncl = dealer NLC (treated as GST-inclusive); selling price is computed in app.js.\n"
    )
    with open(out, "w", encoding="utf-8") as f:
        f.write(header + "const ONORDER = " + json.dumps(items, ensure_ascii=False, indent=2) + ";\n")

    print(f"Wrote {len(items)} on-order items to {out}")
    print(f"  supplier {args.supplier} · brand {args.brand} · valid {args.valid} · GST {args.gst}%")


if __name__ == "__main__":
    main()
